// One off: pull the latin subset woff2 files out of Google Fonts and rewrite the
// @font-face rules to local paths. Run again only when a weight is added.
import fs from 'node:fs';
import path from 'node:path';

const dir = 'public/fonts';
const files = fs.readdirSync(dir).filter((f) => f.endsWith('.css'));
const out = [];
const jobs = [];

for (const f of files) {
  const css = fs.readFileSync(path.join(dir, f), 'utf8');
  const parts = css.split(/\/\*\s*([a-z0-9-]+)\s*\*\//i);
  for (let i = 1; i < parts.length; i += 2) {
    if (parts[i] !== 'latin') continue;
    const block = parts[i + 1];
    const fam = /font-family:\s*'([^']+)'/.exec(block)[1];
    const wgt = /font-weight:\s*([0-9 ]+)/.exec(block)[1].trim().replace(/\s+/g, '-');
    const url = /url\((https:[^)]+)\)/.exec(block)[1];
    const name = fam.replace(/\s+/g, '') + '-' + wgt + '.woff2';
    jobs.push({ url, name });
    let body = block.trim().replace(/^\{/, '').replace(/\}[\s\S]*$/, '');
    body = body.replace(/url\(https:[^)]+\)/, 'url(/fonts/' + name + ')');
    out.push('@font-face {' + body + '}');
  }
}

fs.mkdirSync('src/styles', { recursive: true });
fs.writeFileSync('src/styles/fonts.css', '/* Self hosted. Generated by scripts/fonts.mjs. */\n' + out.join('\n') + '\n');

let ok = 0;
for (const j of jobs) {
  const dest = path.join(dir, j.name);
  if (fs.existsSync(dest)) { ok++; continue; }
  const res = await fetch(j.url);
  if (!res.ok) { console.error('FAIL', j.name, res.status); continue; }
  fs.writeFileSync(dest, Buffer.from(await res.arrayBuffer()));
  ok++;
}
for (const f of files) fs.rmSync(path.join(dir, f));
console.log('faces', out.length, 'files', ok);
